### ISSUE TITLE
Link zum PDF im zweiten Blog-Eintrag ist falsch

### ISSUE THREAD

**Issue by drahkrub** [triologygmbh/jenkinsfile#3]
..., der liefert nämlich das PDF vom ersten Artikel (wenn ich mich nicht total irre).

Wäre super, wenn das korrigiert werden würde!

Ansonsten vielen Dank für die Veröffentlichung!

**Comment by schnatterer** [comment]
@drahkrub Danke für den Hinweis. Das das all die Jahre niemanden aufgefallen ist!

@dhuchthausen das bezieht sich auf den Blog. Könntest du das bitte übernehmen?

**Comment by dhuchthausen** [comment]
Jetzt ist das richtige PDF verlinkt.
